from mcpi.minecraft import Minecraft
mc=Minecraft.create()
x,y,z=mc.player.getPos()
mc.setBlock(x+2,y,z,5)
mc.setBlock(x-2,y,z,5)
mc.setBlock(x+1,y,z+1,5)
mc.setBlock(x-1,y,z+1,5)
mc.setBlock(x,y,z+2,5)
mc.setBlock(x,y,z-2,5)
mc.setBlock(x-1,y,z-1,5)
mc.setBlock(x+1,y,z-1,5)